:le: &#8804;

== Ziccif Extension for Instruction-Fetch Atomicity, Version 1.0

NOTE: This extension was ratified alongside the RVA20U64 profile.
This chapter supplies an operational definition for the extension
and adds expository material.

If the Ziccif extension is implemented, main memory regions with both the
cacheability and coherence PMAs must support instruction fetch, and any
instruction fetches of naturally aligned power-of-2 sizes of at most
`min(ILEN,XLEN)` bits are atomic.

An implementation with the Ziccif extension fetches instructions in a manner
equivalent to the following state machine.

. Let `M` be `min(ILEN,XLEN)/8`, rounded up to the next power of 2.
Let `N` be the `pc` modulo `M`.
Atomically fetch `M` - `N` bytes from memory at address `pc`.
Let `T` be the running total of bytes fetched, initially `M` - `N`.

. If the `T` bytes fetched begin with a complete instruction of length `L` {le}
`T`, then execute that instruction, discard the remaining `T` - `L` bytes
fetched, and go back to step 1, using the updated `pc`.

. Otherwise, atomically fetch `M` bytes from memory at address `pc` + `T`,
increment `T` by `M`, and go back to step 2.

[NOTE]
====
The instruction-fetch atomicity rule supports concurrent code modification.
If a hart modifies instruction memory that it, or other, harts might
execute without first having executed a FENCE.I instruction, it should
adhere to the following rules:

- Modification stores must be single-copy atomic, hence must be naturally
aligned.

- The modified instruction must not span an `M`-byte boundary,
unless it is replaced with a shorter unconditional control transfer
(e.g. `c.ebreak` or `c.j`) that does not itself span an `M`-byte
boundary.

- Modification stores must alter a complete instruction or complete
instructions that do not collectively span an `M`-byte boundary,
modulo the exception above that the first part of an instruction may be
replaced with an unconditional control transfer instruction.

- Modifications may not combine smaller instructions into a larger
instruction but may convert a larger instruction to some number of
smaller instructions.

- Modified instruction memory must have the coherence PMA.

Other well-defined code-modification strategies exist, but these rules provide
a safe harbor.

Note that the software modifying the code need not know the value of `M`.
Because ILEN must be at least the width of the instruction being modified,
a lower bound on `M` can be inferred from the instruction's width and XLEN.
====

== Ziccid Extension for Instruction/Data Coherence, Version 0.1

The Ziccid extension provides a means to describe systems whose
instruction and data memory systems are coherent.
When the Ziccid extension is implemented, instruction fetches appear in the
global memory order, in program order with respect to each other.

NOTE: This in-order fetch property is expected by some JIT compilers.
Straightforward microarchitectures provide this property naturally.
An example of a technique that might violate this property is an instruction
buffer that is populated out of program order, e.g. while fetching down the
predicted path following an instruction-cache miss.
Example solutions include only buffering instructions in program order, or
keeping the buffer coherent by making the coherent instruction cache inclusive
of the buffer.

An instruction fetch from memory with the cacheability and coherence PMAs must
return a value that a load from the same address would have returned, provided
sufficient permissions.

While instruction fetches may still be performed early and
speculatively, they must not be performed earlier than the most recent FENCE.I
instruction, and they must not be succeeded in the global memory order by an
infinite sequence of other memory operations.

NOTE: This definition guarantees that stores _eventually_ become visible to
instruction fetches.
As is the case without the Ziccid extension, a store from the current hart can
be made visible to the hart's instruction fetches in program order by
executing a FENCE.I instruction, or to a remote hart's instruction fetches by
executing a FENCE then requesting (e.g. via IPI) that the remote hart execute
a FENCE.I.


Additionally, any instruction fetches ordered by a FENCE.I instruction must
also be ordered after any explicit memory accesses due to loads and stores
that appear in program order before the FENCE.I.

[NOTE]
====
This requirement facilitates cross-modification of code.
In the following litmus test, for example, the outcome `a0`=1, `a1`=0 on
the consumer thread is forbidden:

```
Initially, flag = 0.

Producer:                                       Consumer:

la t0, patch_me                                 la t0, flag
li t1, 0x4585                                   lw a0, (t0)
sh t1, (t0)   # patch_me := c.li a1, 1          fence.i
fence w, w    # order flag write              patch_me:
la t0, flag                                     c.li a1, 0
li t1, 1
sw t1, (t0)   # flag := 1
```
====

The Ziccid extension depends on the Ziccif extension.

NOTE: Although instruction/data coherence and instruction-fetch atomicity are
conceptually independent properties, the former is much more useful in
conjunction with the latter.
